/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package survivalmk2;

/**
 *
 * @author Floreit
 */
public class SurvivalINT extends javax.swing.JFrame
{
     Storage bank = new Storage();

    /**
     * Creates new form SurvivalINT
     */
    public SurvivalINT()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        PlainsB = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        ForestB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        WoodLabel = new javax.swing.JLabel();
        StoneLabel = new javax.swing.JLabel();
        IronLabel = new javax.swing.JLabel();
        FoodLabel = new javax.swing.JLabel();
        MountainB = new javax.swing.JButton();
        ResetB = new javax.swing.JButton();
        PeopleB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PeopleLabel = new javax.swing.JLabel();
        PeopleModB = new javax.swing.JLabel();
        PeoplemodB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlainsB.setText("Plains");
        PlainsB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PlainsBActionPerformed(evt);
            }
        });

        Label.setText("Stone");

        ForestB.setText("Forest");
        ForestB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ForestBActionPerformed(evt);
            }
        });

        jLabel1.setText("Wood");

        jLabel2.setText("Iron");

        jLabel3.setText("Food");

        WoodLabel.setText("0");

        StoneLabel.setText("0");

        IronLabel.setText("0");

        FoodLabel.setText("0");

        MountainB.setText("Mountain");
        MountainB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MountainBActionPerformed(evt);
            }
        });

        ResetB.setText("Reset");
        ResetB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ResetBActionPerformed(evt);
            }
        });

        PeopleB.setText("Buy Slaves");
        PeopleB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PeopleBActionPerformed(evt);
            }
        });

        jLabel4.setText("People");

        PeopleLabel.setText("1");

        PeoplemodB.setText("ShowPeopleMod");
        PeoplemodB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PeoplemodBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PeopleModB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IronLabel)
                                .addComponent(PeopleLabel)
                                .addComponent(FoodLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StoneLabel)
                                .addComponent(WoodLabel)))
                        .addGap(317, 317, 317)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlainsB)
                            .addComponent(ForestB)
                            .addComponent(MountainB)
                            .addComponent(PeopleB)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PeoplemodB)
                        .addGap(43, 43, 43)
                        .addComponent(ResetB)))
                .addContainerGap(503, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ForestB, MountainB, PeopleB, PlainsB});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {FoodLabel, IronLabel, Label, PeopleLabel, StoneLabel, WoodLabel, jLabel1, jLabel2, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(WoodLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StoneLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IronLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(FoodLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PeopleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PeopleModB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ResetB)
                            .addComponent(PeoplemodB))
                        .addGap(238, 238, 238))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ForestB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PlainsB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MountainB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PeopleB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ForestB, MountainB, PeopleB, PlainsB});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {FoodLabel, IronLabel, Label, PeopleLabel, StoneLabel, WoodLabel, jLabel1, jLabel2, jLabel3, jLabel4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlainsBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PlainsBActionPerformed
    {//GEN-HEADEREND:event_PlainsBActionPerformed
       
        bank.food(1, bank.getpeople());
        bank.people5();
        FoodLabel.setText("" + bank.getfood() );
        PeopleLabel.setText("" + bank.getpeople());
        
    }//GEN-LAST:event_PlainsBActionPerformed

    private void ForestBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ForestBActionPerformed
    {//GEN-HEADEREND:event_ForestBActionPerformed
        bank.wood(1, 11);
        bank.stone(1, 11);
        StoneLabel.setText("" + bank.getstone());
        WoodLabel.setText("" + bank.getwood());                                
    }//GEN-LAST:event_ForestBActionPerformed

    private void MountainBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MountainBActionPerformed
    {//GEN-HEADEREND:event_MountainBActionPerformed
        bank.stone(1, 11);
        bank.iron(1, 11);
        StoneLabel.setText("" + bank.getstone());
        IronLabel.setText("" + bank.getiron());
    }//GEN-LAST:event_MountainBActionPerformed

    private void ResetBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ResetBActionPerformed
    {//GEN-HEADEREND:event_ResetBActionPerformed
       bank.ResetValues();
       FoodLabel.setText("" + bank.getfood());
       IronLabel.setText("" +  bank.getiron());
       StoneLabel.setText("" + bank.getstone());
       WoodLabel.setText("" + bank.getwood());   
       PeopleLabel.setText("" + bank.getpeople());
    }//GEN-LAST:event_ResetBActionPerformed

    private void PeopleBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PeopleBActionPerformed
    {//GEN-HEADEREND:event_PeopleBActionPerformed
        bank.people();
        PeopleLabel.setText("" + bank.getpeople());
        FoodLabel.setText("" + bank.getfood());
    }//GEN-LAST:event_PeopleBActionPerformed

    private void PeoplemodBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PeoplemodBActionPerformed
    {//GEN-HEADEREND:event_PeoplemodBActionPerformed
        PeopleModB.setText("PeopleMod " + bank.getpeoplemod());
    }//GEN-LAST:event_PeoplemodBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SurvivalINT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SurvivalINT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SurvivalINT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SurvivalINT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SurvivalINT().setVisible(true);
            }
        });
        // ----------------------------------------------------------------------
        //                 MAIN 
       
        
        
        
        
        
        
        
        
        //-----------------------------------------------------------------------
        //              End MAIN
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FoodLabel;
    private javax.swing.JButton ForestB;
    private javax.swing.JLabel IronLabel;
    private javax.swing.JLabel Label;
    private javax.swing.JButton MountainB;
    private javax.swing.JButton PeopleB;
    private javax.swing.JLabel PeopleLabel;
    private javax.swing.JLabel PeopleModB;
    private javax.swing.JButton PeoplemodB;
    private javax.swing.JButton PlainsB;
    private javax.swing.JButton ResetB;
    private javax.swing.JLabel StoneLabel;
    private javax.swing.JLabel WoodLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables



}

